<?xml version="1.0"?>
<!--

  Copyright (c) 2011-2012, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--File includes-->
  <xacro:include filename="$(find reem_description)/urdf/deg_to_rad.xacro" />
  <xacro:include filename="$(find reem_description)/urdf/torso/torso.transmission.xacro" />

  <!--Constant parameters-->
  <xacro:property name="torso_max_vel"  value="1.0" />
  <xacro:property name="torso_eps"      value="0.02" />

  <!-- base_link x-axis offset -->
  <xacro:property name="base_link_offset_x" value="-0.0327"/>

  <xacro:macro name="reem_torso" params="name parent">
    <!--************************-->
    <!--        TORSO_1         -->
    <!--************************-->
    <link name="${name}_1_link">
      <inertial>
        <origin xyz="-0.00476 0.00413 0.13972" rpy="0 0 0" />
        <mass value="9.807" />
        <!-- NOTE: Assuming cylinder with r=0.15, h=0.14 -->
         <inertia ixx="0.015591"  ixy="0"  ixz="0" iyy="0.015591" iyz="0" izz="0.024165" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://reem_description/meshes/torso/torso_1.dae"/>
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://reem_description/meshes/torso/torso_1_collision.stl"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_1_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${name}_1_link"/>
      <origin xyz="${-0.108 + base_link_offset_x} 0 0.8725" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${-75.0 * deg_to_rad}" upper="${75.0 * deg_to_rad}" effort="30" velocity="${torso_max_vel}" />
      <dynamics damping="5.0" friction="1.0"/>

      <safety_controller k_position="20"
                         k_velocity="20"
                         soft_lower_limit="${-75.0 * deg_to_rad + torso_eps}"
                         soft_upper_limit="${ 75.0 * deg_to_rad - torso_eps}" />
    </joint>

    <!-- extensions -->
    <xacro:torso_transmission name="${name}_1" reduction="1"/>

    <!--************************-->
    <!--        TORSO_2         -->
    <!--************************-->
    <link name="${name}_2_link">
      <inertial>
        <origin xyz="0.00675 -0.16711 0.00016" rpy="0 0 0"/>
        <mass value="13.299" />
        <!-- NOTE: Assuming box with d=0.2, w=0.4, h=0.46 -->
         <inertia ixx="0.41183"  ixy="0"  ixz="0" iyy="0.22165" iyz="0" izz="0.27884" />
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://reem_description/meshes/torso/torso_2.dae"/>
        </geometry>
        <material name="LightGrey" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://reem_description/meshes/torso/torso_2_collision.stl" />
        </geometry>
      </collision>
    </link>

    <joint name="${name}_2_joint" type="revolute">
      <parent link="${name}_1_link" />
      <child link="${name}_2_link" />
      <origin xyz="-0 0 0.1985" rpy="${-90.0 * deg_to_rad} 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${-15.0 * deg_to_rad}" upper="${45.0 * deg_to_rad}" effort="80" velocity="${torso_max_vel}" />
      <dynamics damping="10.0" friction="1.0"/> <!--NOTE: Joint can do 46.2, but set to higher value because of unmodeled springs-->

      <safety_controller k_position="20"
                         k_velocity="20"
                         soft_lower_limit="${-15.0 * deg_to_rad + torso_eps}"
                         soft_upper_limit="${ 35.0 * deg_to_rad}" />
    </joint>

   <gazebo reference="${name}_1_link">
     <mu1>0.9</mu1>
     <mu2>0.9</mu2>
   </gazebo>
   <gazebo reference="${name}_2_link">
     <mu1>0.9</mu1>
     <mu2>0.9</mu2>
   </gazebo>

   <gazebo reference="${name}_1_joint">
      <cfmDamping>1</cfmDamping>
   </gazebo>
   <gazebo reference="${name}_2_joint">
     <cfmDamping>1</cfmDamping>
     <provideFeedback>1</provideFeedback>
   </gazebo>

    <!-- Torso Front Sonar Ring -->
   <!-- torso sonar right -->
   <xacro:range_reem name="${name}_sonar_14" parent="${name}_2" ros_topic="sonar_torso" update_rate="5" maxRange="0.7" minRange="0.01" fov="0.3491" radiation="ultrasound">
      <origin xyz="0.185 -0.029 -0.075" rpy="0.0 0.0 0.0" />
   </xacro:range_reem>

   <!-- torso sonar left -->
   <xacro:range_reem name="${name}_sonar_15" parent="${name}_2" ros_topic="sonar_torso" update_rate="5" maxRange="0.7" minRange="0.01" fov="0.3491" radiation="ultrasound">
      <origin xyz="0.185 -0.029 0.075" rpy="0.0 0.0 0.0" />
   </xacro:range_reem>

   <!-- torso sonar back -->
   <xacro:range_reem name="${name}_sonar_13" parent="${name}_2" ros_topic="sonar_torso" update_rate="5" maxRange="0.7" minRange="0.01" fov="0.3491" radiation="ultrasound">
      <origin xyz="-0.2 -0.149 0.0" rpy="0.0 ${180.0*deg_to_rad} 0.0" />
   </xacro:range_reem>


    <!-- extensions -->
    <xacro:torso_transmission name="${name}_2" reduction="1" />
  </xacro:macro>

</robot>

